# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: dc34b655b40f019f2f66d4a19cc6dd1db7eb42a1cfa29ca86e9d209b916bf3932c09f31e794d4151abf92a07703d3d5e03d80677fd8aba07d25e7566a03a6eb9
test:
  secret_key_base: 11dfdcb5245ea0ffa1ee9a94d0418fa2573b8da40bef3ca77b7b096657885cb76200c2a02d3833c0b52f877dc671d75c0763701c15839acd0437931f2af38401
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

twilio_sid: '0fe6761da942613b979401cadc61d670'
twilio_token: 0fe6761da942613b979401cadc61d670
twilio_number: "+16822171741"